module BuildMaster
  # JUnit ANT invocation
  class JavaDocAnt
    attr_reader :report
    attr_accessor :src

    def initialize(report)
      @report = report
    end

    def target_name
      'javadoc-ant'
    end

    def generate(build_file = nil)
      build_file = report.file("#{target_name}.xml") unless build_file
      build_file.write do |file|
        file.puts <<BUILD
<!-- ANT file generated by buildmaste JavaDocAnt -->
<project name="#{target_name}" default="#{target_name}">
  <target name="javadoc-ant">
    <javadoc sourcepath="#{src}" destdir="#{report}"/>
  </target>
</project>
BUILD
      end
      build_file
    end

    def run(buildfile = nil)
      buildfile = generate(buildfile)
      report.mkdirs
      AntDriver.new(buildfile).target(target_name)
    end

  end
end
