require File.dirname(__FILE__) + '/../../../lib/buildmaster/auto'
require 'spec'

module BuildMaster
  describe JavaDocAnt do
    it 'should create ANT build file, and jvmargs' do
      cotta = Cotta.new(InMemorySystem.new)
      report = cotta.dir('report')
      javadoc = JavaDocAnt.new(report)
      javadoc.src = cotta.dir('/src')
      actual = javadoc.generate
      build_file = report.file('javadoc-ant.xml')
      actual.should == build_file
      build_file.load.should == <<RESULT
<!-- ANT file generated by buildmaste JavaDocAnt -->
<project name="javadoc-ant" default="javadoc-ant">
  <target name="javadoc-ant">
    <javadoc sourcepath="/src" destdir="report"/>
  </target>
</project>
RESULT
    end

  end
end
