require File.dirname(__FILE__) + '/../../../lib/buildmaster/auto'
require 'spec'

module BuildMaster
  describe PackageAnt do
    it 'should create ant file' do
      cotta = Cotta.new(InMemorySystem.new)
      dir = cotta.dir('root')
      package = PackageAnt.new(dir, 'output')
      package.add(dir.dir('classes'), dir.dir('src'))
      package.add(dir.dir('classes2'))
      build_file = package.build_file
      build_file.load.should == <<RESULT
<!-- ANT file generated by buildmaste PackageAnt -->
<project name="package-ant" default="package-ant">
  <target name="package-ant">
    <jar destfile="#{dir}/output.jar">
      <fileset dir="#{dir}/classes"/>
      <fileset dir="#{dir}/classes2"/>
    </jar>
    <zip destfile="#{dir}/output-src.zip">
      <fileset dir="#{dir}/src"/>
    </zip>
  </target>
</project>
RESULT
    end
  end
end
